// Generated by CoffeeScript 1.6.3
document.addEventListener("DOMContentLoaded", function() {
  var changeClass, classNumber, figure, maxClassNumber;
  figure = document.querySelector(".saffron");
  maxClassNumber = 15;
  classNumber = 1;
  figure.addEventListener("click", changeClass);
  return changeClass = function() {
    figure.classList.remove("c-" + classNumber);
    if (classNumber < maxClassNumber) {
      classNumber++;
    } else {
      classNumber = 1;
    }
    return figure.classList.add("c-" + classNumber);
  };
});
